{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
  ];

  # ── Boot ────────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ── Networking ──────────────────────────────────────────────────────────
  networking.hostName = "nixos"; # Change to match your flake.nix
  networking.networkmanager.enable = true;

  # ── Locale & Time ───────────────────────────────────────────────────────
  time.timeZone = "America/Los_Angeles"; # Change to your timezone
  i18n.defaultLocale = "en_US.UTF-8";

  # ── Wayland / Hyprland ──────────────────────────────────────────────────
  # X11 is not needed — Hyprland runs natively on Wayland.
  services.xserver.enable = false;

  programs.hyprland = {
    enable = true;
    xwayland.enable = true;   # Keeps X11 app compatibility via XWayland
  };

  # GDM for login (Wayland-capable); swap for greetd/tuigreet if preferred
  services.displayManager.gdm = {
    enable = true;
    wayland = true;
  };

  # Wayland-specific environment hints for toolkits
  environment.sessionVariables = {
    NIXOS_OZONE_WL   = "1";   # Electron/Chromium apps use Wayland natively
    MOZ_ENABLE_WAYLAND = "1"; # Firefox Wayland backend
    QT_QPA_PLATFORM  = "wayland";
    SDL_VIDEODRIVER  = "wayland";
    _JAVA_AWT_WM_NONREPARENTING = "1";
  };

  # XDG portal — required for screensharing, file pickers, etc.
  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-hyprland ];
  };

  # ── Sound ───────────────────────────────────────────────────────────────
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };

  # ── User ────────────────────────────────────────────────────────────────
  users.users.apolson = {
    isNormalUser = true;
    description = "Alex Polson";
    extraGroups = [ "networkmanager" "wheel" "video" "audio" ];
    shell = pkgs.zsh;
  };

  # ── System-wide packages (keep this minimal) ────────────────────────────
  environment.systemPackages = with pkgs; [
    wget
    curl
    git
    vim

    # Wayland essentials
    xwayland          # X11 app compatibility layer
    wl-clipboard      # Wayland clipboard (wl-copy / wl-paste)
    cliphist          # Clipboard history manager
  ];

  # ── Shell ───────────────────────────────────────────────────────────────
  programs.zsh.enable = true;

  # ── Nix settings ────────────────────────────────────────────────────────
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };

  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # Required — do not change
  system.stateVersion = "24.11";
}
